# Configuration file for travis-ci.org. Travis is a /continuous integration/ tool that runs tests.
language: python
matrix:
  include:
  - python: "2.7"
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
    # Python 3.7 requires Ubuntu Xenial
    dist: xenial
  - python: "pypy3.5"
sudo: false
addons:
  apt:
    packages:
    - curl
install:
 # Install python-coveralls
 - pip install coveralls
 # pillow is (only) used for examples/map.py
 - pip install pillow
script:
  # run tests/alltests.py (which runs the actual tests)
  # wrap in coverage, which reports the amount of code is covered by the tests.
  - coverage run --source=nbt tests/alltests.py
after_success:
  # Send test coverage results to https://coverage.io/
  coveralls
